### ISSUE TITLE
Add drop-down for reduction choice in Post-Processing

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#113]
Add a dropdown with following options:

- [ ] Bragg
- [ ] PDF

**Comment by JeanBilheux** [comment]
Done in new UI
<img width="345" alt="screen shot 2018-12-06 at 11 30 28 am" src="https://user-images.githubusercontent.com/1138324/49597408-5abc8300-f94a-11e8-82c9-acd5c1cb2487.png">
