### ISSUE TITLE
Since switch to load_ui, icons are not showing up

### ISSUE THREAD

**Issue by JeanBilheux** [neutrons/addie#132]
Issue debated on slack

https://mantid.slack.com/archives/C6KJ6PZEY/p1550065686001300

**Comment by JeanBilheux** [comment]
![ui_main_window-2](https://user-images.githubusercontent.com/1138324/52727227-c5112580-2f82-11e9-892b-426a07bf66ca.png)

**Comment by marshallmcdonnell** [comment]
Closed in https://github.com/neutrons/addie/commit/38e4d21674a62da37b8ae1f83705b23f2ed699c5
