### ISSUE TITLE
Setup testing (with CI)

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#138]
Add simple travis.yml and tests setup.py to do pytest

Mantid conda - https://anaconda.org/mantid/mantid-framework
Mantid docker - https://hub.docker.com/r/mantidproject/mantid/tags

Thoughts:
 - [ ] conda using javelin as an example - https://github.com/rosswhitfield/javelin
 - [ ] docker as well - https://github.com/marshallmcdonnell/mantid_total_scattering

Follow-up will be adding the testing for GUI stuff (model-view-presenter). See Mantid example:
 * https://github.com/mantidproject/mantid/tree/master/qt/python/mantidqt/widgets/samplelogs

**Comment by peterfpeterson** [comment]
This was (mostly) done with #164 and #169.
