### ISSUE TITLE
Renaming tabs (again)

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#139]
For the Mantid selection:
 * disable the first two tabs (`Autoreduce` and `Post-Processing` for IDL)
 * rename `Page` -> `Processing`
 * hide the `File->Configuration` for the Mantid selelction

For other:
 * rename `Autoreduce` -> `autoNOM`
 * rename `Bragg Peaks` -> `Rietveld` (per @peterfpeterson's request)

**Comment by JeanBilheux** [comment]
[ ] Disable the first two tabs when Mantid is selected, and 3rd when IDL is selected. (https://github.com/neutrons/addie/commit/bc0203b01b4af29014b087074620781eb81b0b9e)
[ ] Renamed first 3 tabs

**Comment by JeanBilheux** [comment]
This work has been done.
