### ISSUE TITLE
Fix naming for tabs in modules

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#141]
**Check the boxes and list PRs that fix the re-structure**

Proposed name changes for better structure:
 - [x] `addie.step1` -> `addie.autoNOM` (a7df081802a1a2c82d02e72a4eeb234e1b482993, 3c390c6dbac580a22e72545bb21cdd9817faa7f3)
 - [x] `addie.step2` -> `addie.processing.idl` (495c0cc8b9d282252879b344e6ecca8076b88551)
 - [x] `addie.step3` -> `addie.menu.preview_ascii` (b80bedbb7c396f57fab33bbdeee9f6b68489b993, e1daabe78665564de591c131876eb4ec6fd2de60)
 - [x] `addie.advanced_window_handler` -> `addie.menu.file.settings.advanced_file_window` (53db144f72c2f1748d69c6bb32547d6b9721b0a0)
 - [x] `addie.configuration` -> `addie.menu.file.configuration` (f51dfb8416b84c9d577e5a714de9a2b322895f88)
 - [x] `addie.general_handler` -> `addie.help_handler` (a507f3a7c080617c523e15c20b86cdd83a0b398d)
 - [x] `addie.make_calibration_handler` -> `addie.processing.make_calibration_handler` (fbbe8330d3f863ebd842c9dad0c06603dec81985)
 - [x] `addie.mantid_handler` -> `addie.processing.idl.mantid_handler` (1377d001ce91c6d77c760bb776a4102ac3b3b7a6)
 - [x] `addie.master_table` -> `addie.processing.mantid` (ebc24beee45fcd53e49c5c96fa6be70299dd5f7a)

Make the following modules
 - [x] "loose scripts" -> `addie.rietveld` (df4802f665dad210fd74d6b8b41e30a84c044125)
 - [x] "loose scripts" -> `addie.calculate_gr` (df4802f665dad210fd74d6b8b41e30a84c044125)

These are the "loose scripts"
 - [x] `addie.utilities.oncat.py` -> `addie.databases.oncat` (a0249622fdd9c974e2650f648a358d3693d2baa9)
 - [x] `addie.configuration_initialization.py` -> `addie.initialization.configuration.py` (2c5cc6c13d1d3748d799305ff0e6b0f0340505c1)
 - [x] `addie.customtreeview.py` -> `addie.utilities.customtreeview.py` (515c6d29fb45f45dd032a946f07aa9c0de65aa5b)
 - [x] `addie.edit_sq_dialog.py` -> `addie.calculate_gr.edit_sq_dialog.py` (c070b458ac9bf8fcefea767233a7aa00859f2474)
 - [x] `addie.mplgraphicsview.py` -> `addie.utilities.mplgraphicsview.py` (3ced7a189bd2c7e86019da0ab7d9ca8a5c02edef)
 - [x] `addie.pdf_lines_manager.py` -> `addie.calculate_gr.pdf_lines_manager.py` (ed8210ee9e943de90d429b87a3b61006fd9c4e36)
 - [x] `addie.specify_plots_style.py` -> `addie.utilities.specify_plots_style.py` (d1e545528acc6ec83587ed5732a7bce954b04204)

**Comment by JeanBilheux** [comment]
In order to work on the loose files, I will need some instructions on how to load the data in those tabs and test the various features.

**Comment by marshallmcdonnell** [comment]
If you go to a test ipts then you can look in the SofQ directory for the calculate gr tab and you can go into the GSAS directory for the Bragg Peak tab. You will use the Load S (Q) an Load Bragg buttons respectively and automatically visualize data.


I can also try the branch if you need me to help test

**Comment by JeanBilheux** [comment]
Any good test IPTS? Is 21894 a good one?

**Comment by marshallmcdonnell** [comment]
Sorry away from the computer right now. And without looking into it I couldn't really tell. But I do know ipts 19393 is good to go

**Comment by JeanBilheux** [comment]
no problem. Enjoy your day/trip.
