### ISSUE TITLE
Calculate G(R) - Edit S(Q) re-work

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#203]
Right now updates on moving the slider widget kick off the Fourier Transform, yet this is "dog slow". Instead, probably want to change to the following:
 - `button.pressed.connect(...)` -> Update the value in the Shift / Scale entry
 - `button.released.connect(...)` -> Kick off the calculation

**Comment by JeanBilheux** [comment]
![Screen_Shot_2019-04-03_at_1_37_37_PM](https://user-images.githubusercontent.com/1138324/55500192-ca4f3000-5615-11e9-8251-fb111c9cb54f.png)

**Comment by JeanBilheux** [comment]
Job done as part of a9d32bbc067d4c0b7bb2b8472e47598cb3a3dbba
