### ISSUE TITLE
Calculate G(R) - Get Users attention when no S(Q) selected for Save S(Q)

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#205]
When you do not select an S(Q) from Workspace Tree and click Save S(Q), no error is raised. Should do so (gracefully) to let the User know.

Pop-up to bring it to their attention.

**Comment by JeanBilheux** [comment]
![Screen_Shot_2019-04-03_at_1_44_49_PM](https://user-images.githubusercontent.com/1138324/55500682-c839a100-5616-11e9-989a-f26c00bbb213.png)
