### ISSUE TITLE
Calculate G(r) - Reverse widgets for the Generate G(r) 

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#207]
Makes way more sense for the workflow

**Comment by JeanBilheux** [comment]
![Screen_Shot_2019-04-03_at_1_49_26_PM](https://user-images.githubusercontent.com/1138324/55501071-a391f900-5617-11e9-9824-7cd8b89f8f8c.png)

**Comment by marshallmcdonnell** [comment]
Probably put button below the Qmin Qmax and Rmin, deltaR, and Rmax

**Comment by JeanBilheux** [comment]
![Screen_Shot_2019-04-03_at_1_55_01_PM](https://user-images.githubusercontent.com/1138324/55501305-21560480-5618-11e9-935f-7d64790ae72e.png)
