### ISSUE TITLE
Post-Processing  - Add ability to ouput "AlignAndFocusArgs"  for each per-row JSON

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#211]
Need the ability to add Key-Value pairs (just strings for each right now is fine) so we can add the entry into the JSON. Example:

```
"AlignAndFocusArgs" : { "TMin" : 300.0,
						"TMax" : 16667.0,
						"GroupingWorkspace": "myGroupWksp" }
```

So Key-Value entry 1 would be: "TMin": "300.0" (we can handle casting elsewhere)
and Key-Value entry 3 would be: "GroupingWorkspace": "myGroupWksp"

Thus to add N entries, need a simple "+" button to add each new entry.

**Comment by JeanBilheux** [comment]
https://github.com/neutrons/addie/pull/213
