### ISSUE TITLE
Organization of addie.autoNOM

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#216]
We have code that runs for the Mantid reduction sitting in this module, specifically the `Launch Reduction` for Mantid reduction sits here.
https://github.com/neutrons/addie/blob/master/addie/autoNOM/event_handler.py#L40-L79

Need to move this to enforce the separation between the two and keep the code organized. 

@JeanBilheux do you have a suggestion where this should be moved and what else needs to change accordingly?

**Comment by JeanBilheux** [comment]
because it's related to autoNOM, maybe we should keep it in this folder but inside a file called mantid.py.

**Comment by marshallmcdonnell** [comment]
Actually, those lines of code I pointed out are for the new Mantid reduction and completely unrelated to autoNOM. I agree, needs to move to a separate file and then a different module.

**Comment by JeanBilheux** [comment]
Any suggestions to where to put this code (location and name of module)

**Comment by marshallmcdonnell** [comment]
Maybe in `addie/processing/mantid/master_table/` as `launch_reduction.py`? 

@peterfpeterson, any thoughts?

**Comment by peterfpeterson** [comment]
What about as (I don't have a good filename) `addie/processing/mantid/launch_reduction.py`?

**Comment by marshallmcdonnell** [comment]
@peterfpeterson That's sounds good to me :+1:
