### ISSUE TITLE
When adding global key/value, make sure the one already selected are removed from the list

### ISSUE THREAD

**Issue by JeanBilheux** [neutrons/addie#234]
![Screen Shot 2019-05-07 at 10 29 10 AM](https://user-images.githubusercontent.com/1138324/57307658-f6e1e600-70b2-11e9-9d3d-fc759718bda2.png)

**Comment by marshallmcdonnell** [comment]
This is fixed in current `master` branch. 

Closing this since appears fixed. Feel free to re-open if I am wrong.
