### ISSUE TITLE
Reduction Configuration needs a scroll-bar

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#290]
The Reduction Configuration is statically sized so people with smaller computers cannot reach the bottom of the page to Save and Close or access some options.

**Comment by Kvieta1990** [comment]
Issued solved with pull request [![GitHub issue/pull request detail](https://img.shields.io/github/issues/detail/state/neutrons/addie/339)](https://github.com/neutrons/addie/issues/31902) and therefore will be closed.
