### ISSUE TITLE
Need to connect up the Calibration Creation tool

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#291]
The `Run Calibration` button does not currently launch the calibration but will write out the JSON to run it. Need to add in the `calibration_creation.py` tool to create this calibration

**Comment by Kvieta1990** [comment]
Issue solved with the following PR: [![GitHub issue/pull request detail](https://img.shields.io/github/issues/detail/state/neutrons/addie/344)](https://github.com/neutrons/addie/issues/344)
