### ISSUE TITLE
Add PyStoG as a dependency

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#322]
To support work in PR #321, need to add PyStoG to dependencies

I know we need it in the:

- [x] requirements files
- [ ] environment.yml file
- [x] conda recipe 

May want to also pin the version to at least the major.minor for stability

**Comment by Kvieta1990** [comment]
@marshallmcdonnell Did we already finish this issue? I think the `pystog` dependency has already been added since we now can use the Fourier filter capability (I previously implemented) by using `pystog`.

**Comment by marshallmcdonnell** [comment]
The environment file wasn't yet updated but PR https://github.com/neutrons/addie/pull/337 will fix that once it is merged
