### ISSUE TITLE
PyQt in the Mantid Workbench is now too old to run unit tests using pytest-qt

### ISSUE THREAD

**Issue by marshallmcdonnell** [neutrons/addie#336]
Getting following error for PyQt version being "too old" for pytest-qt
CI log: https://github.com/neutrons/addie/actions/runs/968277326
```
ERROR: PyQt < 5.11 is not supported by pytest-qt, use 5.11+ instead.
```

The upstream Mantid Workbench has still not been able to generate a new conda package for us to use (this is where the Qt + PyQt is defined).
https://anaconda.org/mantid/mantid-workbench/files

The conda recipe was in a "broken" state the last time I was looking at this and seems like little progress has been made.
Recipe location: https://github.com/mantidproject/conda-recipes/

I do know that there have been updates to the Mantid Framework conda package to get it back and working
Maybe using these we can get the Workbench back to working as well.
And Mantid project is suppose to be working on making conda packages "first class citizens" for its distribution so it will probably be fixed eventually for us.

**Comment by Kvieta1990** [comment]
@marshallmcdonnell Thanks a lot to the fix by @rosswhitfield, the CI issue now is fixed! Thank you so much @rosswhitfield !
